// Standalone test for CompletionPdfBuilder against real-world-sized data
// (the actual Cessna 152 pre-boarding checklist's 17 sections / ~157
// items), to visually verify the dense layout before rolling it out to
// any real screen. Not part of the app - run with `dart run` only.
import 'dart:io';
import 'package:pdf/widgets.dart' as pw;
import 'package:clearedtogo/utils/completion_pdf_builder.dart';

void main() async {
  final checklistSections = <String, Map<String, bool>>{
    "CHECK A (ONLY FIRST FLIGHT OF DAY)": {
      "Control Lock                      – REMOVE.": false,
      "Pitot Cover                       – REMOVE.": false,
      "First Aid Kit                    – CHECK.": true,
      "Fire Extinguisher                – CHECK.": true,
      "Magneto Switch                  – OFF.": true,
      "Fuel Shutoff Valve                – ON.": true,
      "Master Switch                     – ON.": true,
      "Flaps                               – FULL (30°).": false,
      "Navigation Light                 – ON.": true,
      "Anti-Collision Light                – ON.": true,
      "Pitot Heater                      – ON.": true,
      "Landing Light                     – ON.": true,
      "External Check (Lights, Pitot Heat, Stall Warner) – ON.": true,
      "All Electrics                      – OFF.": false,
      "Master Switch                     – OFF.": false,
      "Fuel Drains                        – CHECK.": true,
      "Trim, Check Full Range            – ON.": true,
      "Windscreen                         – CLEAR.": true,
    },
    "TRANSIT CHECK (Check A Complete)": {
      "Control Lock                      – REMOVE.": true,
      "Pitot Cover                       – REMOVE.": true,
      "Ignition Switch                  – OFF.": true,
      "Master Switch                     – ON.": true,
      "Fuel Drains                        – CHECK.": true,
      "Fuel Shutoff Valve                – ON.": true,
      "Master Switch                     – OFF.": false,
    },
    "PORT/LEFT WING": {
      "Flap                               – CONDITION, HINGES.": true,
      "Wing Surface (Upper and Lower)   – CONDITION, INSPECTION COVERS IN PLACE.": true,
      "Alieron                            – CONDITION, HINGES, FULL & FREE MOVEMENT.": true,
      "Wing Tip and Navigation Light    – SECURE.": true,
      "Leading Edge                      – CONDITION, AIR INLET CLEAR, FUEL VENT CLEAR.": true,
      "Stall Warner                     – CHECK CLEAR.": true,
      "Pitot Head                       – CHECK CLEAR.": true,
      "Fuel                               – CONTENTS SUFFICIENT, VENT CLEAR, CAP SECURE.": true,
      "Fuel Drain                        – CHECK FOR LEAKS.": true,
      "Landing Gear                     – TYRE CONDITION, BREAK PIPE.": true,
    },
    "FRONT FUSELAGE & ENGINE": {
      "Windscreen                        – CLEAR.": true,
      "Static Source Opening            – CHECK.": true,
      "Engine Intakes                    – CLEAR, ALTERNATOR BELT SECURE": true,
      "Propeller                         – CONDITION, SECURE": true,
      "Nose Wheel Strut and Tire        – CHECK.": true,
      "Engine                            – NO OIL LEAKES": true,
      "Engine Oil Level                 – CHECK (MIN. 4).": true,
      "Fuel Drain                       – CHECK.": true,
    },
    "STARBOARD/RIGHT WING": {
      "Landing Gear                     – TYRE CONDITION, BREAK PIPE.": true,
      "Fuel Drain                        – CHECK FOR LEAKS.": true,
      "Fuel                               – CONTENTS SUFFICIENT, VENT CLEAR, CAP SECURE.": true,
      "Leading Edge                      – CONDITION, AIR INLET CLEAR, FUEL VENT CLEAR.": true,
      "Wing Tip and Navigation Light    – SECURE.": true,
      "Alieron                            – CONDITION, HINGES, FULL & FREE MOVEMENT.": true,
      "Wing Surface (Upper and Lower)   – CONDITION, INSPECTION COVERS IN PLACE.": true,
      "Flap                               – CONDITION, HINGES.": true,
    },
    "REAR FUSELAGE & TAIL": {
      "Rear Fuselage Skin              – CONDITION.": true,
      "Radio Aerials                   – SECURE.": true,
      "Elevator & Trim Tab             – CONDITION, FULL/FREE MOVEMENT, TAB LOCK NUT SECURE": true,
      "Tail Skid                        – CONDITION": true,
      "Fin & Rudder                    – CONDITION, FULL/FREE MOVEMENT, SECURE": true,
      "Beacon & Navigation Light      – SECURE": true,
    },
    "INTERNAL": {
      "Passenger Brief                  – COMPLETE.": true,
      "Cabin Doors                      – CLOSED": true,
      "Seats, Belts, Shoulder Harness  – ADJUST & LOCK.": true,
      "Headset                          – CONNECTED.": true,
      "Trimmer                          – NORMAL RANGE, SET TAKEOFF": true,
      "Circuit Breakers                 – ALL IN.": true,
      "Fuel Shutoff Valve               – ON (HORIZONTAL).": true,
      "Radios & Electrical Equipment    – OFF.": true,
      "Flight Controls                  – FREE & CORRECT.": true,
      "Carburettor Heat                 – CHECK OPERATION, SET COLD": true,
    },
    "ENGINE START": {
      "Battery Master                   – ON.": true,
      "ATC (Start-Up) - IF APPLICIBLE  – REQUEST/NOTIFY.": true,
      "Fuel                             – ON.": true,
      "Radios                           – OFF.": true,
      "Alternator                       – ON.": true,
      "Mixture                          – CHECK OPERATION, SET RICH.": true,
      "Throttle                         – FRICTION LOOSE, CHECK OPERATION, OPEN ¼ INCH.": true,
      "Prime (Up to 3 strokes)          – AS REQUIRED, CHECK LOCKED.": true,
      "Anti-Collision Light/Beacon     – ON.": true,
      "Propeller Area                   – CLEAR.": true,
      "Toe Brakes                       – HOLD ON.": true,
      "Starter                          – OPERATE.": true,
      "RPM                             – SET 1200 RPM.": true,
      "Starter Warning Light            – OUT, IF NOT CLOSE DOWN.": true,
      "Oil Pressure                     – GREEN (<30s).": true,
    },
    "AFTER STARTING": {
      "Headset                         – FITTED & MICROPHONE ADJUSTED, SET SQUELCH.": true,
      "Magnetos                        – DEAD CUT CHECK (L, R, BOTH).": true,
      "Suction                         – WITHIN LIMITS (3 TO 5).": true,
      "Gyro Instruments                – SYNCRONISED DI WITH COMPASS, CHECK AI LEVEL.": true,
      "Ammeter                         – CHARGING": true,
      "Flaps                            – SELECT 30° IN STAGES, RETRACT IN STAGES.": true,
      "Naviagtion Aids                 – TUNED, TESTED, IDENTIFIED.": true,
      "Transponder                     – SET 7000, TEST, SET STBY.": true,
      "Radios                          – TUNED, AUDIO PANEL SET, VOL SET, CALL.": true,
      "Altimeter                       – SET QFE OR QNH, CHECK WITHIN LIMITS.": true,
      "Time & Hobbs                    – RECORD": true,
    },
    "TAXI": {
      "ATC (Taxi)                       – REQUEST/NOTIFY.": true,
      "Brake Check                      – PERFORM.": true,
      "Flight Instruments               – CHECK (Compass, Gyro, Turn Coordinator, AI).": true,
    },
    "POWER CHECKS": {
      "Aircraft                       – INTO WIND, CLEAR BEHIND.": true,
      "Toe Brakes                      – HOLD ON.": true,
      "Oil Temperature               – SUFFICIENT FOR RUN UP.": true,
      "Throttle                      – SET 1700 RPM, CHECK BRAKES HOLDING.": true,
      "Alternator                      – FUNCTIONING, CHECK AMMETER CHARGING.": true,
      "Suction                      – SUFFICIENT (APPROX 5 REQUIRED).": true,
      "Carburettor Heat              – HOT, CHECK DROP, SET COLD.": true,
      "Magnetos                      – CHECK, L, R, BOTH (MAX DROP 125RPM, MAX DIFFERENCE 50RPM).": true,
      "Throttle                      – CLOSE IDLE (500-700RPM), MIN OIL PRESSURE 25PSI, SET 1200RPM.": true,
    },
    "PRE TAKE-OFF": {
      "Elevator Trim                    – TAKEOFF.": true,
      "Throttle Friction Lock           – ADJUSTED.": true,
      "Mixture                          – RICH.": true,
      "Carburetor Heat                  – CHECK OPERATION.": true,
      "Magnetos                         – CHECK.": true,
      "Fuel Shutoff Valve               – ON (HORIZONTAL).": true,
      "Primer                           – LOCKED.": true,
      "Flaps                            – SET (UP / 10°).": true,
      "Flight Instruments               – CHECK (Compass, Gyro, Turn Coordinator, AI).": true,
      "Gauges                           – WITHIN LIMITS, CHECK OAT.": true,
      "Pitot Heat                      – AS REQUIRED (ON IF OAT <5°C).": true,
      "Cabin Doors                      – CLOSED.": true,
      "Seats, Seat Belts & Harnesses    – ADJUST & LOCK.": true,
      "Flying Controls                 – FULL AND FREE MOVEMENT.": true,
      "Transponder                      – ALT.": true,
      "Landing & Strobe Lights          – ON.": true,
    },
    "AFTER TAKE-OFF": {
      "Flaps                            – UP.": true,
      "Engine                           – T'S & P'S.": true,
      "Trim                             – SET .": true,
    },
    "TOP OF CLIMB, CRUISE, APPROACH": {
      "Fuel                             – CONTENTS SUFFICIENT.": true,
      "Radio                            – FREQ, TEST VOL AND TRANSPONDER.": true,
      "Engine                           – CARB HEAT, GAUGES.": true,
      "DI & Compass                      – DI & COMPASS.": true,
      "Altimeter                        – QNH OR 1013 OR QFE.": true,
      "Landing & Strobe Lights          – ON.": true,
    },
    "LANDING - CHEF": {
      "Carburettor Heat                  – ON.": true,
      "Harnesses                        – SECURE.": true,
      "Engine                           – GAUGES.": true,
      "Fuel                             – CONTENTS CHECK, MIXTURE RICH.": true,
      "Carburettor Heat                  – OFF (300FT).": true,
    },
    "AFTER LANDING": {
      "Clear of Runway                  – STOP.": true,
      "Carburetor Heat                  – COLD.": true,
      "Flaps                            – UP.": true,
      "Trimmer                          – NEUTRAL.": true,
      "Throttle Friction Nut            – SLACKEN.": true,
      "Pitot Heat                       – OFF.": true,
      "Landing & Strobe Lights          – OFF.": true,
      "Transponder & Nav Aids           – OFF.": true,
      "Fuel Contents                    – CHECK & REFUEL IF NECESSARY.": true,
    },
    "SHUTDOWN": {
      "Toe Brakes                       – OFF (IN).": true,
      "Throttle                         – 1200 RPM.": true,
      "Time & Hobbs                     – RECORD.": true,
      "Magnetos                         – DEAD CUT CHECK (L, R, BOTH).": true,
      "Radios                           – OFF.": true,
      "Throttle                         – OFF.": true,
      "Mixture                          – IDLE CUT OFF.": true,
      "Magneto Switch                  – WHEN ENGINE STOPPED, REMOVE KEY.": true,
      "Master Switch                    – OFF.": true,
      "Harnesses                        – STOWED NEATLY.": true,
      "Control Locks                    – IN.": true,
      "Pitot Cover                      – ON.": true,
      "Chocks                           – AS REQUIRED.": true,
    },
  };

  final fontBytes = await File('assets/fonts/NotoSans-Regular.ttf').readAsBytes();
  final font = pw.Font.ttf(fontBytes.buffer.asByteData());

  final bytes = await CompletionPdfBuilder.build(
    font: font,
    title: 'Cessna 152 Pre-boarding Checklist',
    aircraftType: 'Cessna 152',
    completedAt: DateTime.now(),
    pilotName: 'Alex Morgan',
    licenseNumber: 'PPL(A) 123456',
    homeBase: 'EGLL',
    data: checklistSections,
  );

  final outPath = r'C:\Users\thoma\AppData\Local\Temp\claude\c--Users-thoma-OneDrive-Desktop-app-flutter-application-1\0ac8e2c4-cf49-4374-9f3b-4abb8d794f82\scratchpad\test_checklist.pdf';
  await File(outPath).writeAsBytes(bytes);
  print('wrote $outPath (${bytes.length} bytes)');
}
